# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sebastian Gulinski
email: sebastian.gulinski@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Reflection of my views and opinions on various aspects of software development, 
  building effective teams and great engineering cultures with a dash of financial
  markets in the mix.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sgulinski.com" # the base hostname & protocol for your site
permalink: "/:title"

# Uncomment the following two lines to remove disclaimer from your website
# exclude: [disclaimer.md]
# exclude_disclaimer_link_from_footer:	true

# Social media settings
twitter_username: sgulinski
github_username:  sgulinski
linkedin_public_link:	sgulinski
stackoverflow_user:	3689153
stackoverflow_display_name:	sebastian-gulinski

# Build settings
markdown: kramdown
